language: java
jdk:
  - openjdk8
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_cc3bd1153744_key -iv $encrypted_cc3bd1153744_iv
    -in application-apikey.properties.enc -out common/src/main/resources/application-apikey.properties -d
  - chmod +x gradlew
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.gradle"
script: "./gradlew clean build"
after_success:
  - "./gradlew jacocoRootReport coveralls"
notifications:
  email:
    recipients:
      - ehd0309@naver.com
dd:
